ticketee/config/routes.rb
Ticketee::Application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :users
  end

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/awaiting_confirmation',
  :to => "users#confirmation",
  :as => 'confirm_user'

  root :to  =>"projects#index"
  resources :projects do
    resources :tickets
  end

end

ticketee/app/models/ability.rb
class Ability
  include CanCan::Ability

  def  initialize(user)
    user.permissions.each do |permission|
      can permission.action.to_sym,
      permission.thing_type.constantize do |thing|
        thing.nil? ||
          permission.thing_id.nil? ||
          permission.thing_id == thing.id
      end
    end
  end
end

ticketee/app/models/permission.rb
class Permission < ActiveRecord::Base
  attr_accessible :user, :action, :thing

  belongs_to :user
  belongs_to :thing, :polymorphic => true
end

ticketee/app/models/project.rb
class Project < ActiveRecord::Base

  def self.for(user)
    user.admin? ? Project : Project.viewable_by(user)
  end

  attr_accessible :description, :name

  scope :admins, where(:admin => true)

  validates :name, :presence => true, :uniqueness => true

  has_many :permissions, :as => :thing
  def self.viewable_by(user)
    joins(:permissions).where(:permissions => { :action => "view", :user_id => user.id})
  end

  has_many :tickets, :dependent => :delete_all

end

ticketee/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  attr_accessible :description, :title
  validates :title, :presence => true
  validates :description, :presence => true,
  :length => { :minimum => 10 }
end

ticketee/app/models/user.rb
class User < ActiveRecord::Base
  # include default devise modules.  Others available are:
  # :token_authenticatable, :encyptable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :password, :admin, :as => :admin

  has_many :permissions

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
  # attr_accessible :title, :body
end

ticketee/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authorize_admin!
  def index

  end
end

ticketee/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_filter :find_user, :only => [:show, :edit, :update, :destroy]

  def index
    @users = User.all(:order => "email")
  end

  def new
    @user = User.new
  end

  def show

  end

  def edit

  end

  def update
    @user.skip_reconfirmation!
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update_attributes(params[:user], :as => :admin)
      flash[:notice] =   "User has been updated."
      redirect_to  admin_users_path
    else
      flash[:alert] = "User has not been updated."
      render :action => "edit"
    end
  end


  def create
    @user = User.new(params[:user], :as => :admin)
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[alert] = "User has not been created."
      render :action => "new"
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

end

ticketee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  before_filter :mailer_set_url_options

  protect_from_forgery

#  def mailer_set_url_options
#    ActionMailer::Base.default_url_options[:host] = request.host_with_port
#  end

  private

  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end
  
end

ticketee/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize_admin!, :except =>[:index, :show]
  before_filter :authenticate_user!, :only => [:index, :show]
  before_filter :find_project, :only => [:show,
                                         :edit,
                                         :update,
                                         :destroy]

  def index
    @projects = Project.for(current_user).all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
      else
        flash[:alert] = "Project has not been created."
        render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking" +
      " for could not be found."
    redirect_to projects_path
  end

end

ticketee/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def after_inactive_sign_up_path_for(resource)
    confirm_user_path
  end
end

ticketee/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :find_project
  before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]
  before_filter :authorize_create!, :only => [:new, :create]
  before_filter :authorize_update!, :only => [:edit, :update]
  before_filter :authorize_delete!, :only => :destroy

  def new
    @ticket = @project.tickets.build
  end

  def show
  end

  def edity

  end


  def create
    @ticket = @project.tickets.build(params[:ticket])
    @ticket.user = current_user
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new"
    end
  end

  def update
    if @ticket.update_attributes(params[:ticket])
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been updated."
      render :action =>"edit"
    end
  end
  
  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."
    redirect_to @project
  end
  
  private
  def find_project
    @project = Project.for(current_user).find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to root_path
  end

  def find_ticket
    @ticket = @project.tickets.find(params[:id])
  end

  def authorize_create!
    if !current_user.admin? && cannot?("create tickets".to_sym, @project)
      flash[:alert] = "You cannot create tickets on this project."
      redirect_to @project
    end
  end

  def authorize_update!
    if !current_user.admin? && cannot?("edit tickets".to_sym, @project)
      flash[:alert] = "You cannot edit tickets on this project."
      redirect_to @project
    end
  end

  def authorize_delete!
    if !current_user.admin? && cannot?(:"delete tickets", @project)
      flash[:alert] = "You cannot delete tickets from this project."
      redirect_to @project
    end
  end
end

ticketee/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def confirmation
  end
end

ticketee/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

ticketee/app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end

  def admins_only(&block)
    concat(block.call) if current_user.try(:admin?)
  end

  def authorized?(permission, thing, &block)
    block.call if can?(permission.to_sym, thing) || current_user.try(:admin?)
  end

end

ticketee/app/helpers/projects_helper.rb
module ProjectsHelper
end

ticketee/app/helpers/tickets_helper.rb
module TicketsHelper
end

ticketee/app/helpers/users_helper.rb
module UsersHelper
end

ticketee/app/views/admin/base/index.html.erb
<%= link_to "Users", admin_users_path %>
Welcome to Ticketee's Admin Lounge. Please enjoy your stay.

ticketee/app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :email  %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password  %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.check_box :admin  %>
    <%= f.label :admin, "Is an admin?" %>
  </p>
  <%= f.submit %>
<% end %>

    

ticketee/app/views/admin/users/edit.html.erb
<h2>Editing a User</h2>
<%= render "form" %>

ticketee/app/views/admin/users/index.html.erb
<!---
<h1>Admin::Users#index</h1>
<p>Find me in app/views/admin/users/index.html.erb</p>
-->

<%=link_to "New User", new_admin_user_path %>
<ul id='users'>
  <% @users.each do |user| %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

ticketee/app/views/admin/users/new.html.erb
<h2>New User</h2>
<%= render "form" %>

ticketee/app/views/admin/users/show.html.erb
<h2><%= @user %></h2>
<%= link_to "Edit User", edit_admin_user_path(@user) %>

ticketee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for(:title) %>
    <%= yield(:title) %>
    <% else %>
    Ticketee
    <% end %>

  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%flash.each do |key,value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %> 

<nav>
  <% if user_signed_in? %>
  Signed in as <%= current_user.email %>
  <% admins_only do %>
    <%= link_to "Admin", admin_root_path %>
  <% end %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</nav>

<%= yield %>

</body>
</html>

ticketee/app/views/projects/_form.html.erb
<%= form_for(@project)  do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

ticketee/app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render "form" %>

ticketee/app/views/projects/index.html.erb
<% admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>
<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
  <li><%= link_to project.name,project %></li>
  <% end %>
</ul>

ticketee/app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render "form" %>

ticketee/app/views/projects/show.html.erb
<% title(@project.name,"Projects") %>
<h2><%= @project.name%></h2>

<% admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project",
      project_path(@project),
      :method => :delete,
      :confirm => "Are you sure you want to delete this project?" %>
<% end %>
<% authorized?("create tickets".to_sym, @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>
<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
  <li>
    #<%= ticket.id %> -
    <%= link_to ticket.title, [@project, ticket] %>
  <li>
  <% end %>
</ul>

ticketee/app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br>
    </programlisting>
    </informalexample>
    <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :description %><br>
      <%=f.text_area :description %>
    </p>
    <%= f.submit %>
    <% end %>

ticketee/app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

ticketee/app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>

ticketee/app/views/tickets/show.html.erb
<div id='ticket'>
  <h2><%= @ticket.title %></h2>
  <span id='author'>Created by <%= @ticket.user.email %></span>

  <%= authorized?("edit tickets", @project) do %>
    <%= link_to "Edit Ticket", [:edit, @project, @ticket] %>
  <% end %>

  <%= link_to "Delete Ticket", [@project, @ticket], :method => :delete,
  :confirm => "Are you sure you want to delete this ticket?" %>

  <%= simple_format(@ticket.description) %>
</div>

ticketee/app/views/users/confirmation.html.erb
<h1>You have signed up successfully</h1>

Please confirm your account before signing in.